####  Hidden Markov Model (HMM)

In [ ]:
import numpy as np

Evaluation Problem

In [ ]:
# Given Data from Example 1 from course

# transition probabilities
a = np.array([[1, 0, 0, 0],[0.2, 0.3, 0.1, 0.4],[0.2, 0.5, 0.2, 0.1],[0.7, 0.1, 0.1, 0.1]])

# emission probabilities
b = np.array([[1, 0, 0, 0, 0],[0.0, 0.3, 0.4, 0.1, 0.2],[0.0, 0.1, 0.1, 0.7, 0.1],[0.0, 0.5, 0.2, 0.1, 0.2]])

# observables
x = np.array(['x0','x1','x2','x3','x4'])

# hidden states
z = np.array(['z0','z1','z2','z3'])

# sequence of observations
k = [1,3,2,0]

# states
N = len(z)

# time
T = len(x)

In [ ]:
print(f'aij = \n{a}')
print(f'\nbjk = \n{b}')
print(f'\nx = \n{x}')
print(f'\nz = \n{z}')
print(f'\nk = \n{k}')

aij = 
[[1.  0.  0.  0. ]
 [0.2 0.3 0.1 0.4]
 [0.2 0.5 0.2 0.1]
 [0.7 0.1 0.1 0.1]]

bjk = 
[[1.  0.  0.  0.  0. ]
 [0.  0.3 0.4 0.1 0.2]
 [0.  0.1 0.1 0.7 0.1]
 [0.  0.5 0.2 0.1 0.2]]

x = 
['x0' 'x1' 'x2' 'x3' 'x4']

z = 
['z0' 'z1' 'z2' 'z3']

k = 
[1, 3, 2, 0]


In [ ]:
# Initialize for all j : alpha[j](0)

alpha = np.zeros((N,T))
for j in range(0, N):
  if j==1: #Initial state z(0) = z1
    alpha[j][0] = 1
  else:
    alpha[j][0] = 0

print(f'Initialisation of alpha : \n {alpha}')

Initialisation of alpha : 
 [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
def evaluation_problem(a, b, N, T, alpha):
  for t in range(1, T):
    for j in range(0, N):
      temp = 0
      for i in range(0, N):
        temp += alpha[i, t-1]*a[i, j]
      alpha[j, t] = temp*b[j, k[t-1]]
  P = alpha[0, T-1]
  print('HMM forward algorithm :\n')
  print(alpha)
  return P

In [ ]:
# print(*range(0,T), sep='\t       ')

PxM = evaluation_problem(a, b, N, T, alpha)
print(f'\nP(x|M) = α0(4) = {PxM}')
print("\nThe above value is the probability that our model HMM M generated for x = {x1, x3, x2, x0}, \nwhere M is defined by {aij}, {bjk} and αj (0).")

HMM forward algorithm :

[[0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 1.8218e-03]
 [1.0000e+00 9.0000e-02 5.2000e-03 5.1920e-03 0.0000e+00]
 [0.0000e+00 1.0000e-02 2.1700e-02 5.4300e-04 0.0000e+00]
 [0.0000e+00 2.0000e-01 5.7000e-03 9.6400e-04 0.0000e+00]]

P(x|M) = α0(4) = 0.0018218000000000002

The above value is the probability that our model HMM M generated for x = {x1, x3, x2, x0}, 
where M is defined by {aij}, {bjk} and αj (0).


Decoding Problem


In [ ]:
def decoding_problem(a, b, N, T, alpha):
  path = [1]
  for t in range(1, T):
    for j in range(0, N):
      temp = 0
      for i in range(0, N):
        temp += alpha[i, t-1]*a[i, j]
      alpha[j, t] = temp*b[j, k[t-1]]
    jprime = np.argmax(alpha[:,t]) 
    path.append(jprime)
  return path

In [ ]:
Path = decoding_problem(a, b, N, T, alpha)

print(f'Decoding problem \n\nPath = {Path}')
print(f"\nHence, for each time step, we only consider the hidden state that is the most probable. \nThen, the sequence of states through which the model transits while generating x is: z{Path[0]}, z{Path[1]}, z{Path[2]}, z{Path[3]}, z{Path[4]}.")

Decoding problem 

Path = [1, 3, 2, 1, 0]

Hence, for each time step, we only consider the hidden state that is the most probable. 
Then, the sequence of states through which the model transits while generating x is: z1, z3, z2, z1, z0.
